// Originally generated by Lovable; now maintained by hand. The shared key/fetch
// helpers live in ./api-key.ts — edit them there, not here.
import { createClient } from "@supabase/supabase-js";
import { isPlaceholder } from "@/lib/config/validate";
import { assertSupabaseConfig, createSupabaseFetch } from "./api-key";
import type { Database } from "./types";

/**
 * SSR fallback for the public values. Guarded because `process` does not exist
 * in a browser: reading `process.env` there throws a ReferenceError that
 * replaces a precise configuration error with an inscrutable one.
 */
function serverEnv(name: string): string | undefined {
  return typeof process !== "undefined" ? process.env[name] : undefined;
}

function createSupabaseClient() {
  // import.meta.env is replaced at build time for the browser bundle;
  // process.env is the SSR fallback. Only the publishable key is ever exposed
  // here — the service role key must never reach this module.
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"] || serverEnv("SUPABASE_URL");
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || serverEnv("SUPABASE_PUBLISHABLE_KEY");

  assertSupabaseConfig({
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
  });

  // VITE_ values are inlined at build time, so a bundle built without real
  // public config carries a placeholder into every browser and Supabase answers
  // `401 Invalid API key` on every request. Naming the cause here turns that
  // into a one-line diagnosis instead of an auth investigation.
  const placeholders = (
    [
      ["VITE_SUPABASE_URL", SUPABASE_URL],
      ["VITE_SUPABASE_PUBLISHABLE_KEY", SUPABASE_PUBLISHABLE_KEY],
    ] as const
  )
    .filter(([, value]) => isPlaceholder(value))
    .map(([name]) => name);

  if (placeholders.length > 0) {
    throw new Error(
      `Supabase public configuration holds placeholder value(s): ${placeholders.join(", ")}. ` +
        "This bundle was built without real public config; rebuild with the correct " +
        "VITE_* values. Every Supabase request would otherwise fail with 'Invalid API key'.",
    );
  }

  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
