// Originally generated by Lovable; now maintained by hand. The shared key/fetch
// helpers live in ./api-key.ts — edit them there, not here.
//
// Phase 1 fix: Authorization header injection moved into a per-request fetch
// wrapper so it is applied AFTER supabase-js builds its own header set.
// This prevents the SDK from clobbering the user JWT with the apikey value
// on some serverFn request paths, which caused intermittent 401s.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import { assertSupabaseConfig, createSupabaseFetch } from "./api-key";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env["SUPABASE_URL"];
    const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

    assertSupabaseConfig({ SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY });

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    // Structural pre-check: a real access token has three non-empty JWT segments.
    const parts = token.split(".");
    if (parts.length !== 3 || parts.some((p) => p.length === 0)) {
      throw new Error("Unauthorized: Invalid token");
    }

    // Authorization is injected inside the fetch wrapper so it is applied last
    // and cannot be overwritten by supabase-js's own header merging logic.
    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: (input, init) => {
          const baseFetch = createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!);
          const headers = new Headers(init?.headers);
          headers.set("Authorization", `Bearer ${token}`);
          return baseFetch(input, { ...init, headers });
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub as string,
        claims: data.claims,
      },
    });
  },
);
