// Originally generated by Lovable; now maintained by hand. The shared key/fetch
// helpers live in ./api-key.ts — edit them there, not here.
//
// Server-side Supabase client using the service role key. It bypasses RLS, so it
// is for admin operations inside server functions and server routes only. For
// user-scoped queries that must obey RLS, use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import { assertSupabaseConfig, createSupabaseFetch } from "./api-key";
import type { Database } from "./types";

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const SUPABASE_SERVICE_ROLE_KEY = process.env["SUPABASE_SERVICE_ROLE_KEY"];

  assertSupabaseConfig({
    SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY,
  });

  return createClient<Database>(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY!, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY!),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// SECURITY: service role — bypasses RLS. Never expose to client code.
// Load inside server handlers:
//   const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// A top-level import is safe only from other .server.ts modules; route files and
// *.functions.ts files ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
